class TwitterCredentials():
    API_KEY='NNVq017qyzQiSUsobeXuoA'
    API_SECRET='llYoDUUHN6kKGNdxidwHwiMrIeWVWmNI5DPFkx0AYo'
    ACCESS_TOKEN='52416153-4FX5fFVq7NZmftK3JsiPaSqUQup3mrTCPg4euMEfJ'
    ACCESS_TOKEN_SECRET='dzZ1iKXNFF74FiVzEJ0bKQmTU5UeInQoIBbrDDoUekVQf'